import type { Metadata } from 'next';

// These styles apply to every route in the application
import './globals.css';
import DesktopUi from './DesktopUi';
import MobileUi from './MobileUi';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="lg:flex justify-center h-screen">
          <div className="hidden lg:flex justify-center max-w-[450px]">
            <DesktopUi />
          </div>
          <div className="lg:overflow-auto">
            <MobileUi>{children}</MobileUi>
          </div>
        </div>
      </body>
    </html>
  );
}
